version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: LaravelTable
      MYSQL_ROOT_PASSWORD: nisum123
      MYSQL_USER: root
      MYSQL_PASSWORD: nisum123
    volumes:
      - ./mysql:/var/lib/mysql
